### ISSUE TITLE
Wrong names of Congo in geocoder

### ISSUE THREAD

**Issue by sorokins** [daviddrysdale/python-phonenumbers#117]
```
>>> phone = phonenumbers.parse('+243 1123 32 12', None)
>>> geocoder.country_name_for_number(phone, 'en')
u'The Democratic Republic Of Congo'
```

"The Democratic Republic Of Congo" is wrong name, the right is "Democratic Republic of the Congo".

```
>>> phone = phonenumbers.parse('+242 1123 32 12', None)
>>> geocoder.country_name_for_number(phone, 'en')
u'Congo'
```
"Congo" is wrong too, real name is "Republic of the Congo"

**Comment by daviddrysdale** [comment]
Please report upstream

**Comment by sorokins** [comment]
I cloned google's libphonenumber and searched through the code by "Congo" and did not find anything looks like country name. Also I see that country names are located in phonenumbers/geodata/locale.py in your lib (not in "resources" copied from google) So I guess, country names should be fixed in your code.
Am I wrong?

**Comment by daviddrysdale** [comment]
Ah, apologies -- I assumed this was coming from the [per-region phonenumber data](https://github.com/googlei18n/libphonenumber/tree/master/resources/geocoding) rather than the per-country data.

However, it's still data where the master copy is elsewhere -- only in this case the data [gets extracted](tools/python/DumpLocale.java) from the locale information that Java makes available.

So there's not much I can do in this codebase to fix it, I'm afraid.
