### ISSUE TITLE
format phone number to "country_code + area_code + local_nummer + direct_dialing"

### ISSUE THREAD

**Issue by Koyirov** [daviddrysdale/python-phonenumbers#118]
Hello,
I am trying to format a phone number to 
	`country_code + area_code + local_number + direct_dialling.`
I  think it is currently only possible to format a phone number to
	`country_code + area_code + phone_number.`
Is there a way to format a phone number according to the first example ?

**Comment by daviddrysdale** [comment]
Not that I know of -- the set of [available formats](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L394) is limited, partly because there are few formats that work for all the different regions in the world -- it's worth reading the [upstream project](https://github.com/googlei18n/libphonenumber)'s list of [gotchas](https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md) (especially numbers 12, 19, and 21).

**Comment by Koyirov** [comment]
Thank you for your answer. Can we then apply this formatting only to these particular countries? I haven't found anything from phonenumber's library.
