### ISSUE TITLE
PhoneNumber class methods and attributes

### ISSUE THREAD

**Issue by vesauimonen** [daviddrysdale/python-phonenumbers#14]
Is there a reason why PhoneNumber class doesn't have methods and attributes for validation and formatting the phone number? For templates and such it would seem easier to just write `phone_number.international` or `phone_number.is_valid()` instead of using `phonenumbers.is_valid_number(phone_number)` for example.

This seems to me like a design issue or maybe there's something I'm missing. Hopefully someone can clarify me.

Anyways I ended up writing my own PhoneNumber class. I'm not sure if there's a reason why the class was not designed this way.

``` python
import phonenumbers

class PhoneNumber(phonenumbers.phonenumber.PhoneNumber):
    def __init__(self, raw_number, country_code=None):
        self._phone_number = phonenumbers.parse(raw_number, country_code)
        super(PhoneNumber, self).__init__(
            country_code=self._phone_number.country_code,
            national_number=self._phone_number.national_number,
            extension=self._phone_number.extension,
            italian_leading_zero=self._phone_number.italian_leading_zero,
            raw_input=self._phone_number.raw_input,
            country_code_source=self._phone_number.country_code_source,
            preferred_domestic_carrier_code=
            self._phone_number.preferred_domestic_carrier_code
        )
        self.national = phonenumbers.format_number(
            self._phone_number,
            phonenumbers.PhoneNumberFormat.NATIONAL
        )
        self.international = phonenumbers.format_number(
            self._phone_number,
            phonenumbers.PhoneNumberFormat.INTERNATIONAL
        )
        self.e164 = phonenumbers.format_number(
            self._phone_number,
            phonenumbers.PhoneNumberFormat.E164
        )

    def is_valid(self):
        return phonenumbers.is_valid_number(self._phone_number)
```

**Comment by daviddrysdale** [comment]
The main reason why the code is designed this way is to keep the structure of the Python code as a close mirror of the [upstream Java codebase](https://code.google.com/p/libphonenumber/).  I made some minor changes to pythonize things (described in the [internal README](https://github.com/daviddrysdale/python-phonenumbers/blob/dev/tools/python/README)), but larger design changes would make it harder to merge upstream changes and keep things in sync.

I don't know for sure why the upstream codebase has these methods on the `PhoneNumberUtil` singleton rather than the `PhoneNumber` class, but I suspect it's because the `PhoneNumber` class is just supposed to be a lightweight class for storing and transmitting phonenumbers.   In particular, its base definition is a protobuf, hence no methods (other than getters and setters) in the class itself.
