### ISSUE TITLE
Over Aggressive Matching for US numbers

### ISSUE THREAD

**Issue by tnmcneil** [daviddrysdale/python-phonenumbers#169]
I am trying to parse only US phone numbers out of a document that contains numbers from multiple countries - mainly US, and the non US numbers are in E164 format which I will grab in a later parse
The issue is I am getting international numbers in E164 format found in the parse, and also they are marked as valid numbers even though the parse shows their country code to be something other than 1.
(the offending phone numbers in question are +420 222 888 888, +44 20 7493 1232 and +36 1 486 5000.)
This is not reproducible in the Java demo: http://libphonenumber.appspot.com/phonenumberparser?number=44+20+7483+1232&country=US
In the above link you can see isValidNumber is False.
To reproduce:
```
# first pass for US numbers
for match in PhoneNumberMatcher(content, "US"):
    parsed = parse(match.raw_string, "US")
    if is_valid_number(parsed):
        print(match.number)
# second pass for other numbers in E164 format
for match in PhoneNumberMatcher(content, "US"):
    parsed = parse(match.raw_string, "US")
    if is_valid_number(parsed):
        print(match.number) 
```
I would eventually add a filter on the second loop to not return numbers which were previously found as american.
example content:
```
Dr. Paul can be reached at +420 222 888 888.  His assistant's personal phone number is 800-922-8228, but sometimes you can call him at 9163249078.  His associate can be reached before 9am at +1-202-435-4325.  When he is traveling you can try his international cell at +44 20 7493 1232 or his wife's international number at +36 1 486 5000.
```

**Comment by daviddrysdale** [comment]
Ah, I think you're mis-using the region/country argument to the `PhoneNumberMatcher` constructor: 
```
country -- The country to assume for phone numbers not written in
              international format (with a leading plus, or with the
              international dialing prefix of the specified region).
```

It's not intended to filter discovered phonenumbers by region, it's there to allow discovery & parsing of non-E164 phonenumbers (because a non-E164 number is not globally unique).

So you probably want to do a single pass with region as `"US"` (assuming that's where your text is from), and then if you want just US/NANPA numbers, filter the resulting `PhoneNumber` objects by their `country_code`
