### ISSUE TITLE
Packaging phonenumbers in a stand-alone executable?

### ISSUE THREAD

**Issue by gitdjc** [daviddrysdale/python-phonenumbers#192]
I'm still struggling with creating a stand-alone executable of a program that uses phonenumbers-lite. The aim is to provide stand-alone executables for Windows and Macs to relatively naive users who don't have -- or simply don't want -- Python installed on their systems.

The barrier seems to be how to package and include in the executable metadata that would, in the interpreted environment, be dynamically loaded. So far I've tried only pyinstaller, with which I've produced stand-alone executables for other Python programs, but if another packager would work, I'd use that.

Has anyone done this? How? Or have you some concrete suggestion for where to begin?

**Comment by daviddrysdale** [comment]
I guess the problem is that `phonenumbers` does some trickery with `__import__` to load metadata files at runtime (to avoid the occupancy overhead of loading the whole world's metadata).  

Assuming that's the case, I can think of a couple of possible avenues:
 - [The PyInstaller docs have some hints about dealing with users of `__import__`](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html?highlight=__import__)
 - Locally modify the [on-demand loading code](https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/phonenumbers/data/__init__.py#L21-L30) to just `import` everything there and then.

For the first of those, did https://github.com/pyinstaller/pyinstaller/issues/3381 not help?
