### ISSUE TITLE
international numbers error

### ISSUE THREAD

**Issue by jaross** [daviddrysdale/python-phonenumbers#20]
Check the number like 0011404abcdefg (where a-g a digit) in the context of a region having 00 as the international prefix, e.g., PL. parse returns 1 and 404... and I think 0011404... is an incorrect international number dialed from PL (should be 001404...)

Best
js

**Comment by daviddrysdale** [comment]
Hi, You closed this before I could take a look -- did you figure out your problem?

**Comment by jaross** [comment]
I am not sure so I decided to close it (I should have left a comment...
sorry)
so, considered a number +1 404 483 abcd which is a valid number. Now, go to
a region that accepts international prefix 00. this number is valid there
as 001404483abcd and 0011404483... The second form was strange to me but I
think I was wrong and should not have issued the ticket. Anyway I could not
confirm it works or not this way from a 00-prefix region.

Sorry
js

**Comment by daviddrysdale** [comment]
I've not worked through the details, but I'd guess this is because 1+10D is a valid way of dialling US numbers within the US.  So 00114044831234 becomes:
- 00 for international dialling
- 1 for NANPA country code
- 1 for US dialling prefix (I think historically used to indicate long-distance calls)
- 404 for NPA
- 483 for NXX
- 1234 for subscriber.

By the way, a good place to check validation results is http://libphonenumber.appspot.com/.  That runs the upstream Java code, so if it shows the same results it implies there's nothing specific to the Python version involved.

**Comment by jaross** [comment]
Thank you!

js
