### ISSUE TITLE
Porting to Python 3

### ISSUE THREAD

**Issue by aaugustin** [daviddrysdale/python-phonenumbers#21]
Hello, this isn't really an issue, but I don't know where else to talk about this.

I need to use phonenumbers with Python 3.3.

The README talks about:
- running 2to3, but I'm not sure how well that plays with pip.
- the python3 branch, but the wording doesn't inspire a lot of confidence.

Current porting efforts keep compatibility with Python 2.5, which makes the shared-source approach one order of magnitude harder than targeting Python 2.6 as the lowest supported version.

Since I have some experience with porting to Python 3 (I ported Django, among other things), I tried to redo the porting for 2.6+ and 3.3+, which is all I need. It just required the following steps:
- making relative imports explicit eg. `from .util import ...`
- changing `try` blocks to use the `except ... as ...` syntax
- removing long literals; I'm not sure why they're used instead of plain integers; this change makes a lot of noise in the tests
- replacing `long` by `int`
- adding `text_type` (`unicode` or `str`) and `xrange` (`xrange` or `range`) for compatibility
- replacing `sys.maxint` by something else -- I used `sys.maxsize` but that's semantically wrong, another hardcoded constant would be better

At this point, the library appears to work ie. I can reproduce the examples in the documentation. However, for some reason, the tests (python setup.py test) fail massively, as if no data could be found for any country.

Finally I suggest the following fix to UnicodeMixin:

```
 class UnicodeMixin(object):  # pragma no cover
     """Define __str__ operator in terms of __unicode__ for Python 2/3"""
+    # Emulate the way the interpreter looks up magic methods
     if sys.version_info >= (3, 0):
-        __str__ = lambda x: x.__unicode__()
+        __str__ = lambda x: type(x).__unicode__(x)
     else:
-        __str__ = lambda x: unicode(x).encode('utf-8')
+        __str__ = lambda x: type(x).__unicode__(x).encode('utf-8')
```

It shouldn't matter except in weird subclassing schemes.

This isn't really actionnable, and I expect you to close this issue once you've read it, but I found it interesting to share this experience. 

[EDIT] I accidentally sumbitted the issue while I was writing, I've completed my description since then.

**Comment by daviddrysdale** [comment]
I think that the `python3` branch is functionally complete (the changes in it are very similar to the ones you suggest), it's just that 
- I don't always push metadata changes to it as frequently as to the dev branch
- I wasn't aware of anyone using it in anger.

So I can start keeping the `python3` branch up to date if I know someone out there is seriously using it.  That will also give the branch more mileage, which will increase my confidence in it, which should mean I can make it the main branch sooner rather than later.

To that end, I've just merged up the 5.6 release into it -- do you want to give it a try?

(I added the Python3 section to the README to try to bring some Python3 users out of the woodwork, so I'm glad that worked...)

**Comment by kvesteri** [comment]
The python 3 branch works like a charm - thanks. I'm currently developing many open source projects that use this wonderful library. I think it would make sense to use six (https://pypi.python.org/pypi/six/) for python compatibility issues. We could then use just one branch for phonenumbers package and target python versions 2.6, 2.7 and 3.3.

**Comment by daviddrysdale** [comment]
The `python3` branch already supports Python 2.5-2.7 as well as 3.x, so my aim is indeed to make that the one true branch for the project -- but I wanted to hear from some real-world users of that branch first (so thanks for letting me know it works fine for you).

And you're right, it might make sense to drop in [six](https://pypi.python.org/pypi/six/) rather than sticking with my own [hand-hacked equivalent](https://github.com/daviddrysdale/python-phonenumbers/blob/python3/python/phonenumbers/util.py), but there are a few project-specific extras in there too -- I'll take a look at what conversion would involve.

**Comment by daviddrysdale** [comment]
Hmm, on a quick play I've already hit a problem with six -- `six.print_(six.u(r"\\"))` gives different results with Python 2.7 and 3.2 (`\` vs `\\`).  So I'll stick with the current approach for now.

**Comment by daviddrysdale** [comment]
OK, the main `dev` branch is now the dual-mode version.

I'll leave the `python3` branch present, but it won't be updated from now on.

**Comment by aaugustin** [comment]
Great!
