### ISSUE TITLE
valid French number is considered as invalid

### ISSUE THREAD

**Issue by lpetic** [daviddrysdale/python-phonenumbers#241]
I tried the following code:
```py
import phonenumbers


x = phonenumbers.parse("+33.616343502", None)
print(phonenumbers.is_valid_number(x))  # True it's okay

x = phonenumbers.parse("+33.690629042", None)
print(phonenumbers.is_valid_number(x))  # False but should be True
```

Python version: Python 3.9.7
library version: 8.12.49 & 8.12.47

**Comment by daviddrysdale** [comment]
Upstream code [gives same result](https://libphonenumber.appspot.com/phonenumberparser?number=%2B33.690629042)

**Comment by lpetic** [comment]
@daviddrysdale why this is considered as an invalid number? For my, it’s a valid phone number.

**Comment by mde-pach** [comment]
@inlor 
`+33690` prefix is not valid regarding the standard because the french number range `+33690` is reserved for international equivalent `+5906690` a kind of "convertion" for local phone numbers for the consumer that is international in a telecom context.

https://en.wikipedia.org/wiki/Telephone_numbers_in_France#Guadeloupe,_Saint-Barth%C3%A9lemy_and_Saint-Martin

```python
>>> phonenumbers.is_valid_number(phonenumbers.parse("+33.690629042", None))
False
>>> phonenumbers.is_valid_number(phonenumbers.parse("+590.690629042", None))
True
>>> 
```
