### ISSUE TITLE
number_type returns 0 for CoutryCode and NationalNumber on  DE region

### ISSUE THREAD

**Issue by vbasha** [daviddrysdale/python-phonenumbers#245]
Python Phonenumbers version  8.12.52
Facing the issue on Jul19/2022.I could see the latest version 8.12.52 relased on same date.

from phonenumbers import carrier
from phonenumbers.phonenumberutil import number_type
from phonenumbers.phonenumberutil import parse

        phone_number = 4917684119883 # phone number with contry code
        print(parse(str(phone_number), region=str('DE'))) // Country Code: 49 National Number: 4917628881467
        print(number_type(parse(str(phone_number), region=str('DE')))) // returns 0
  The previous release number_type(parse(str(phone_number), region=str('DE'))) returns as 1, so conclude that valid mobilenumber.But with  latest 8.12.52  version  returns as 0.
        
Why the number_type returns PhoneNumberType.FIXED_LINE not the PhoneNumberType.MOBILE

**Comment by daviddrysdale** [comment]
- Confirmed that this result changed between v8.12.51 and v8.12.52. 
- The upstream v8.12.52 Java code gives [the same result (`FIXED_LINE`)](https://libphonenumber.appspot.com/phonenumberparser?number=4917684119883&country=DE).
- There were only metadata changes in v8.12.52.
   -  Upstream [release notes](https://github.com/google/libphonenumber/blob/master/release_notes.txt) include "Updated phone metadata for region code(s): .. **DE** ..."
- So the difference must be due to a metadata change, which should be reported [upstream](https://github.com/google/libphonenumber).
