### ISSUE TITLE
How to define your own format?

### ISSUE THREAD

**Issue by chrisspen** [daviddrysdale/python-phonenumbers#248]
Is there any way to define your own format?

I have an application where I need to store numbers formatted like "(800) 123-4567", but after looking through all the possible built-in formats, I don't think you have anything exactly like this. The closest I could find was "US", but that formats it like "800-123-4567".

How would I implement this format?

**Comment by daviddrysdale** [comment]
It's not very well documented, but `format_by_pattern` might do what you want:

```pycon
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import phonenumbers
>>> from phonenumbers import format_by_pattern, PhoneNumberFormat, NumberFormat
>>> n = phonenumbers.parse("(800) 123-4567", "US")
>>> f = NumberFormat(pattern="(\\d{3})(\\d{3})(\\d{4})", format="(\\1) \\2-\\3")
>>> format_by_pattern(n, PhoneNumberFormat.NATIONAL, [f])
'(800) 123-4567'
```

However, supplying your own format is likely to be very specific to a particular region, and won't cope with arbitrary international numbers.  (It's also not usually a good idea to store formatted numbers rather than `PhoneNumber` objects, because the formatted number is region-specific and subject to changes in display formats.)
