### ISSUE TITLE
Carrier response returns blank info

### ISSUE THREAD

**Issue by masterseo2000** [daviddrysdale/python-phonenumbers#251]
Hello all,
I have installed phonenumber (not phonenumberlite) while looking up  a particular phone number I’m getting almost everything but the carrier and that is precisely the carrier that I’m looking for.   (FYI I am not the programmer) I was wondering if The Programmer is missing a step like downloading the data set for a particular country or carrier.
Also since we’re talking about carrier data how accurate is that data given the huge number of porting requests (people that change the number from one Carrier to the other on a daily basis)
Thanks for your help! If I can make this work for us that would be wonderful ❤️

**Comment by daviddrysdale** [comment]
Please could you provide more details about what entrypoints aren't working and what version of the library you're using.  

For example, does the sample code from the README work?

```pycon
>>> import phonenumbers
>>> from phonenumbers import carrier
>>> ro_number = phonenumbers.parse("+40721234567", "RO")
>>> carrier.name_for_number(ro_number, "en")
'Vodafone'
```

Carrier portability is addressed in the upstream FAQ [here](https://github.com/google/libphonenumber/blob/master/FAQ.md#since-its-possible-to-change-the-carrier-for-a-phone-number-how-is-the-data-kept-up-to-date).

**Comment by daviddrysdale** [comment]
Closing due to lack of detail.
