### ISSUE TITLE
Geocoding results in Traditional Chinese

### ISSUE THREAD

**Issue by fawkeswei** [daviddrysdale/python-phonenumbers#26]
How the original java library parse language code
- `zh` -> simplified chinese
- `zh-tw` -> traditional chinese
- `zh_Hant` -> unknown locale, use english

But python library 
- `zh` -> simplified chinese
- `zh-tw` unknown locale, use english
- `zh_Hant` -> traditional chinese

Below is the code demonstrating the problem 

```
>>> from phonenumbers.geocoder import area_description_for_number
>>> print area_description_for_number(phonenumbers.parse("0800080123", "TW"), "zh")
屏东
>>> print area_description_for_number(phonenumbers.parse("0800080123", "TW"), "zh_tw")
Pingtung  // should be 屏東
>>> print area_description_for_number(phonenumbers.parse("0800080123", "TW"), "zh_Hant")
屏東 // should be Pingtung
```

> > Just for reference 
> > - 屏东 <- simplified chinese 
> > - 屏東 <- traditional chinese

**Comment by daviddrysdale** [comment]
OK, there's a few things to note here.

First of all, I probably shouldn't have exposed the `area_description_for_number` function, as the equivalent `getAreaDescriptionForNumber` Java method is private.  The expected entrypoint to use is `getDescriptionForNumber` / `description_for_number`.

However, that entrypoint will actually fallback to 'Taiwan' / 台湾地区 for +886800080123, because it's a toll-free number (it fails the `canBeGeocoded` / `_can_be_geocoded` test).  But shifting to use +886810080123 instead (i.e. avoiding the 0800 national prefix) gets us back to hitting the +8868.... geodata.

Next, I should point out that in the Python code both the `description_for_number` and `area_description_for_number` actually expect multiple arguments (lang/Script/REGION), not a combined lang_script / lang_region code.

The same is true for the (private) Java `getAreaDescriptionForNumber` entrypoint, but the public `getDescriptionForNumber` Java entrypoint actually takes a `java.util.Locale` object (and so you'd need to use `Locale.Builder` to get a `Locale` with a specific script value).

So putting that together I get:

``` pycon
>>> import phonenumbers
>>> x = phonenumbers.parse("0810080123", "TW")
>>> print phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.E164)
+886810080123
>>> from phonenumbers.geocoder import description_for_number
>>> print description_for_number(x, "zh")
屏东
>>> print description_for_number(x, "zh", script="Hant")
屏東
>>> print description_for_number(x, "zh", region="TW")
屏东
>>> print description_for_number(x, "en")
Pingtung
```

i.e. Python has:

```
+886810080123
zh => 屏东
zh/Hant => 屏東
zh/TW => 屏东
en => Pingtung
```

And then Java code like

``` java
PhoneNumberOfflineGeocoder geocoder = PhoneNumberOfflineGeocoder.getInstance();
PhoneNumberUtil pnu = PhoneNumberUtil.getInstance();
PhoneNumber x = new PhoneNumber().setCountryCode(886).setNationalNumber(810080123);
System.out.println(pnu.format(x, PhoneNumberFormat.E164));
Locale zh = new Locale("zh");
System.out.println("zh (" + zh + ") => " + geocoder.getDescriptionForNumber(x, zh));
Locale zh_Hant = new Builder().setLanguage("zh").setScript("Hant").build();
System.out.println("zh/Hant (" + zh_Hant + ") => " + geocoder.getDescriptionForNumber(x, zh_Hant));
Locale zh_TW = new Locale("zh", "TW");
System.out.println("zh/TW (" + zh_TW + ") => " + geocoder.getDescriptionForNumber(x, zh_TW));
Locale en = new Locale("en");
System.out.println("en (" + en + ") => " + geocoder.getDescriptionForNumber(x, en));
```

gives Java output:

```
+886810080123
zh (zh) => 屏东
zh/Hant (zh__#Hant) => 屏东
zh/TW (zh_TW) => 屏東
en (en) => Pingtung
```

So even with the details tweaked, the results are still different between Python and Java.

**Comment by daviddrysdale** [comment]
Aha, the Python code was missing the `LOCALE_NORMALIZATION_MAP` that translates `zh_TW` into `zh_Hant`.  That direction should be fixed in commit 2ea483bfa9ac19144183dadaa7cafb2772a72bfe.

**Comment by daviddrysdale** [comment]
For the other direction, the Java code is [explicitly not retrieving](https://code.google.com/p/libphonenumber/source/browse/trunk/java/geocoder/src/com/google/i18n/phonenumbers/geocoding/PhoneNumberOfflineGeocoder.java#162) a script value from a full `Locale` object, and so a request for locale `zh/Hant` is treated as just a request for locale `zh`.

**Comment by daviddrysdale** [comment]
BTW, I'm told the different functionality in the Java version is because of a Java limitation (`java.util.Locale` didn't expose any script information until 1.7), so I'm going to leave the Python behaving as now.
