### ISSUE TITLE
IE164 contains trailing zero (should be removed)

### ISSUE THREAD

**Issue by tobenary** [daviddrysdale/python-phonenumbers#285]
Hi all,
I am having an issue with the trailing zero that are attatched to the IE164 number format.

See picture below, When parsing the number (as an example: '+10368667383') it identifying it has leading zeros (good), but the IE164 format still contains it. (should be removed)

commands used:
```
phonenumbers.parse('+10368667383', None) > Parsed correctly with trailing zero
phonenumbers.is_possible_number(phonenumbers.parse('+10368667383', None))  > True
phonenumbers.format_number(phonenumbers.parse('+10368667383', None), phonenumbers.PhoneNumberFormat.E164)
> '+10368667383'
```

<img width="651" alt="fHEYSUyzEw" src="https://github.com/daviddrysdale/python-phonenumbers/assets/8009594/b52d4bee-a76c-44be-a312-db076bc37d90">

Python version 3.11.3
library version 8.13.25

**Comment by daviddrysdale** [comment]
The Python output is consistent with the upstream code <https://libphonenumber.appspot.com/phonenumberparser?number=%2B10368667383>, so this is not an issue with the Python code.

**Comment by tobenary** [comment]
Thanks, I checked the site you mentioned before, but it gave me an "invalid" in the IE164 number -  Where the Python code did output the number, that's why I submitted this bug.

@daviddrysdale , 
I'm wondering if a bypass could be taking the parsed country code (with the Plus sign) and adding it to the national number will do the trick.  like:
f"\+{parsed.country_code}{parsed.national_number}"   > +1368667383

**Comment by daviddrysdale** [comment]
The number here is possible but not valid, so I re-opened this to check the behaviour of the Python code vs the Java code when calling `format_number(invalid_numobj, E164)`.

The Java demo code [skips output of E164 format](https://github.com/google/libphonenumber/blob/3d2127540df035c376245638868e627e5d0d8e3c/javascript/i18n/phonenumbers/demo.js#L127) for invalid numbers, so a simple comparison of the demo output vs. the Python output is misleading. (Running `appspot.py --number +10368667383` gives the same as the demo output, because that Python helper utility also has the invalid-check.)

Bypassing the invalid-check in the Java code results in the Java code emitting the same value as the Python code, so closing again as the behaviour is the same.
