### ISSUE TITLE
Cannot install dev branch from pip

### ISSUE THREAD

**Issue by justjkk** [daviddrysdale/python-phonenumbers#7]
I want to use pip to install from the `dev` branch. But it fails because setup.py is not found in the repository root.

The following syntax is used to install straight from git repository:

``` bash
sudo pip install git+git://github.com/daviddrysdale/python-phonenumbers.git@dev
```

Is it possible to move setup.py to the repository root to fix this? Alternatively, is it possible to run dev branch without maintaining a git clone of the repository on the target system?

**Comment by daviddrysdale** [comment]
Hmm.  

On the one hand, this is clearly pip's [problem](https://github.com/pypa/pip/issues/209) &ndash; which has affected a [few](https://bugs.launchpad.net/pycrypto/+bug/629455) [other](http://code.google.com/p/gflags/issues/detail?id=31) [projects](http://code.google.com/p/protobuf/issues/detail?id=66) in the past.  There might even be a [pip fix](https://github.com/pypa/pip/pull/526) in the works.

On the other hand, [multiple](https://groups.google.com/forum/#!msg/python-virtualenv/QpbUPWCPCs4/5XVYVpergesJ) [folk](https://github.com/patrickod/python-phonenumbers/commit/0767b1510dcb90683aef6dceb2f7e1af8c4710ee) [would](https://github.com/erydo/python-phonenumbers/commit/3a7d387cc9ad733092ca7b2670228d9dbc5dc30a) [apparently](https://github.com/vpotter/python-phonenumbers/commit/d2ac6ed7d08cd35fcf47d920c14b195d61beb064) like this, so maybe I should take the hint.

On the third hand, there's a chance that the Python codebase might someday get folded into the [master upstream Google codebase](http://code.google.com/p/libphonenumber/) (which is why the code is in a `python/` subdir in the first place), and in that structure having a `setup.py` in the top-level directory probably won't work.

Need to ponder more...

**Comment by daviddrysdale** [comment]
That `setup.py` seems to allow the pip command to work.

**Comment by justjkk** [comment]
@daviddrysdale, thanks for the quick fix. Pip install works now.
