### ISSUE TITLE
Wrong parse phone number

### ISSUE THREAD

**Issue by trungnq1510** [daviddrysdale/python-phonenumbers#84]
i used parse function to check the input is phone or not. But it parsed wrong in this case.
phone_check = phonenumbers.parse("VNTRIP2016A0NLH", "VN")
and parse result is : 
PhoneNumber(country_code=84, national_number=201620654, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=None, preferred_domestic_carrier_code=None).

**Comment by daviddrysdale** [comment]
The upstream Java code gives the [same result](http://libphonenumber.appspot.com/phonenumberparser?number=VNTRIP2016A0NLH&country=VN), so this isn't something that's specific to the Python port.  You could raise against the upstream project, but I imagine this is expected due to alpha->number [mapping](https://en.wikipedia.org/wiki/Phoneword).
